site_name: Red Hat Openshift studies
repo_url: https://github.com/jbcodeforce/openshift-studies
nav:
  - Introduction: index.md
  - Kubernetes fundamentals:
    - Introduction: k8s/k8s-0.md
    - Networking: k8s/k8s-1.md
    - Security: k8s/k8s-2.md
    - FAQ: k8s/k8s-faq.md
    - Compendium: k8s/k8s-comp.md
  - Docker tricks: docker.md
  - Openshift: 
      - cp4i: cp4i.md
      - FAQ: faq.md
      - oc CLI: oc-cli.md
      - Deployment examples: deployment-ex.md
      - notes certification: notes-ocp-training.md
  - Knative: knative.md
  - SRE: sre.md
  - Operators (with Spark): spark-on-os.md
  - Open Data Hub: opendatahub.md
  - Istio: istio/readme.md
  - Ansible: ansible.md
  - ODO - Appsody Summary: odo-appsody.md
  - Compendium: compendium.md

theme: 
  name: material
  palette:
    primary: red
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences