site_name: Red Hat Openshift studies
repo_url: https://github.com/jbcodeforce/openshift-studies
nav:
  - Introduction: index.md
  - Kubernetes deeper dive:
    - Kubernetes introduction: k8s/k8s-0.md
    - Networking: k8s/k8s-1.md
    - Security: k8s/k8s-2.md
    - Demo it: k8s/k8s-3.md
    - FAQ: k8s/k8s-faq.md
    - Notes from certification: notes-ocp-training.md
    - Compendium: k8s/k8s-comp.md
  - Use Openshift: 
      - Cloud Native Development: os-cn-dev.md
      - Cloud Pak Integration: cp4i.md
      - FAQ: faq.md
      - oc CLI: oc-cli.md
      - Deployment examples: deployment-ex.md
      - Operators (with Spark): spark-on-os.md
  - Operations:
    - SRE: sre.md
    - Ansible: ansible.md
    - Operators (with Spark): spark-on-os.m
  - Compendium: compendium.md
  - Back to home: https://jbcodeforce.github.io/
theme: 
  name: material
  palette:
    primary: red
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.details